---
name: Checks

# trigger is a git push
on: [push]

jobs:
  test-lint:
    name: Test and Lint
    # the runner (OS) for job, comes with docker-compose pre-installed
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        # using a premade github action
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"

      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"

